In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import csv
import re
import nltk
import random
import string

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS , ImageColorGenerator


from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer


from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

import nltk
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize

import numpy as np 
import pandas as pd
import seaborn as sns
import csv
import re
import nltk
import random
import string

import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS , ImageColorGenerator


from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer


from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

import os, sys, logging, traceback, codecs, datetime, copy, time, ast, math, re, random, shutil, json, csv, multiprocessing, subprocess
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import os
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import itertools
import collections
import sklearn
from sklearn.feature_extraction.text import CountVectorizer


import nltk
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')



import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
import nltk 
import string
import re
%matplotlib inline
from wordcloud import WordCloud, STOPWORDS , ImageColorGenerator

from collections import Counter
from sklearn.model_selection import GridSearchCV

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from xgboost import XGBClassifier

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/Hartej/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Hartej/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/Hartej/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/Hartej/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
#Import Dataset 

data = pd.read_csv('./SP_News.csv', sep=',', index_col='Date', parse_dates=True)

#data = pd.read_csv('./SP_News.csv', sep=',', parse_dates=True)

In [3]:
# Formatting / Cleaning

In [4]:
data.head()

Open     High      Low    Close  Adj Close      Volume
Date                                                                 
2017-12-22  2684.22  2685.35  2678.13  2683.34    2683.34  2399830000
2017-12-26  2679.09  2682.74  2677.96  2680.50    2680.50  1968780000
2017-12-27  2682.10  2685.64  2678.91  2682.62    2682.62  2202080000
2017-12-28  2686.10  2687.66  2682.69  2687.54    2687.54  2153330000
2017-12-29  2689.15  2692.12  2673.61  2673.61    2673.61  2443490000

In [5]:
print('Dataset size:',data.shape)
print('Columns are:',data.columns)
print(data.dtypes)

Dataset size: (644, 6)
Columns are: Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object


In [6]:
#Values missing  = NO

data.isnull().sum()

Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [7]:
# Change the datatype of the volume column to float
data['Volume'] = data['Volume'].astype(float)

In [8]:
# Remove columns which you can't use as features
data.drop(['Open', 'High', 'Low', 'Adj Close'], axis=1, inplace=True)

In [9]:
data.head()

Close        Volume
Date                             
2017-12-22  2683.34  2.399830e+09
2017-12-26  2680.50  1.968780e+09
2017-12-27  2682.62  2.202080e+09
2017-12-28  2687.54  2.153330e+09
2017-12-29  2673.61  2.443490e+09

In [10]:
#Transform into Supervised Problem 

In [11]:
#Create new column for price difference 

data['Difference']= data['Close'].diff()
data.dropna(inplace = True)

data

#Divide by previous day? 

Close        Volume  Difference
Date                                         
2017-12-26  2680.50  1.968780e+09       -2.84
2017-12-27  2682.62  2.202080e+09        2.12
2017-12-28  2687.54  2.153330e+09        4.92
2017-12-29  2673.61  2.443490e+09      -13.93
2018-02-01  2695.81  3.367250e+09       22.20
...             ...           ...         ...
2020-10-07  3185.04  4.515340e+09       32.99
2020-07-13  3155.22  4.890780e+09      -29.82
2020-07-14  3197.52  4.476170e+09       42.30
2020-07-15  3226.56  4.669760e+09       29.04
2020-07-16  3215.57  3.961230e+09      -10.99

[643 rows x 3 columns]

In [12]:
#Find daily Stock Trend -> Binary

Rise = 1 
Fall = 0 

data['Trend'] = np.where(
    data['Difference'] > 0, Rise, Fall
)

data

Close        Volume  Difference  Trend
Date                                                
2017-12-26  2680.50  1.968780e+09       -2.84      0
2017-12-27  2682.62  2.202080e+09        2.12      1
2017-12-28  2687.54  2.153330e+09        4.92      1
2017-12-29  2673.61  2.443490e+09      -13.93      0
2018-02-01  2695.81  3.367250e+09       22.20      1
...             ...           ...         ...    ...
2020-10-07  3185.04  4.515340e+09       32.99      1
2020-07-13  3155.22  4.890780e+09      -29.82      0
2020-07-14  3197.52  4.476170e+09       42.30      1
2020-07-15  3226.56  4.669760e+09       29.04      1
2020-07-16  3215.57  3.961230e+09      -10.99      0

[643 rows x 4 columns]

In [13]:
#Target is next day's Trend

data['Target'] = data.Trend.shift(-1)
data.dropna(inplace = True)

data

Close        Volume  Difference  Trend  Target
Date                                                        
2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0
2017-12-27  2682.62  2.202080e+09        2.12      1     1.0
2017-12-28  2687.54  2.153330e+09        4.92      1     0.0
2017-12-29  2673.61  2.443490e+09      -13.93      0     1.0
2018-02-01  2695.81  3.367250e+09       22.20      1     1.0
...             ...           ...         ...    ...     ...
2020-09-07  3152.05  4.829020e+09      -17.89      0     1.0
2020-10-07  3185.04  4.515340e+09       32.99      1     0.0
2020-07-13  3155.22  4.890780e+09      -29.82      0     1.0
2020-07-14  3197.52  4.476170e+09       42.30      1     1.0
2020-07-15  3226.56  4.669760e+09       29.04      1     0.0

[642 rows x 5 columns]

In [14]:
data.to_csv("sp_news_cleaned_data.csv")

In [15]:
#Train Test Split 

In [16]:
def train_test_split(data,perc):
    data = data.values
    n = int(len(data) * (1 - perc))
    return data[:n], data[n:]

In [17]:
train, test = train_test_split(data,0.2)

In [18]:
print (len(data))
print (len(train))
print (len(test))

642
513
129


In [19]:
#train = np.array(train)
#test = np.array(test)

In [20]:
data

Close        Volume  Difference  Trend  Target
Date                                                        
2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0
2017-12-27  2682.62  2.202080e+09        2.12      1     1.0
2017-12-28  2687.54  2.153330e+09        4.92      1     0.0
2017-12-29  2673.61  2.443490e+09      -13.93      0     1.0
2018-02-01  2695.81  3.367250e+09       22.20      1     1.0
...             ...           ...         ...    ...     ...
2020-09-07  3152.05  4.829020e+09      -17.89      0     1.0
2020-10-07  3185.04  4.515340e+09       32.99      1     0.0
2020-07-13  3155.22  4.890780e+09      -29.82      0     1.0
2020-07-14  3197.52  4.476170e+09       42.30      1     1.0
2020-07-15  3226.56  4.669760e+09       29.04      1     0.0

[642 rows x 5 columns]

In [21]:
#data = data.values
#test = test[train.columns]

In [22]:
#Seperate x and y features 

x_train = train[:, :-1]
y_train = train[:, -1]

x_test = test[:, :-1]
y_test = test[:, -1]

In [23]:
# Remove columns which you can't use as features
#data.drop(['Difference'], axis=1, inplace=True)

In [24]:
x_train


array([[ 2.68050e+03,  1.96878e+09, -2.84000e+00,  0.00000e+00],
       [ 2.68262e+03,  2.20208e+09,  2.12000e+00,  1.00000e+00],
       [ 2.68754e+03,  2.15333e+09,  4.92000e+00,  1.00000e+00],
       ...,
       [ 3.23718e+03,  3.42038e+09, -9.10000e+00,  0.00000e+00],
       [ 3.25305e+03,  3.72089e+09,  1.58700e+01,  1.00000e+00],
       [ 3.27470e+03,  3.63839e+09,  2.16500e+01,  1.00000e+00]])

In [25]:
y_train

array([1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 1.

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_scaler = scaler.fit(x_train)
x_train = x_scaler.transform(x_train)
x_test = x_scaler.transform(x_test)

#Scaler made no difference 

In [27]:
#Test

In [28]:
#Score classifier -> Basic 

model = XGBClassifier()
model.fit(x_train, y_train.ravel())

train_score = model.score(x_train, y_train)
test_score = model.score(x_test, y_test)

print('Train score: ', train_score)
print('Test score: ', test_score)

[15:29:02] WARNING: /opt/concourse/worker/volumes/live/7a2b9f41-3287-451b-6691-43e9a6c0910f/volume/xgboost-split_1619728204606/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Train score:  0.9980506822612085
Test score:  0.5581395348837209


In [29]:
#Predict classifier -> Basic 

predictions = model.predict(x_test)

pd.DataFrame({
    'Prediction': predictions,
    'Trend': y_test.ravel()
})

Prediction  Trend
0           0.0    1.0
1           0.0    0.0
2           1.0    1.0
3           1.0    1.0
4           0.0    1.0
..          ...    ...
124         0.0    1.0
125         1.0    0.0
126         0.0    1.0
127         1.0    1.0
128         1.0    0.0

[129 rows x 2 columns]

In [30]:
#Evaluation

In [31]:
accuracy = accuracy_score(y_test, predictions)

print(accuracy)

0.5581395348837209


In [33]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.50      0.47      0.49        57
         1.0       0.60      0.62      0.61        72

    accuracy                           0.56       129
   macro avg       0.55      0.55      0.55       129
weighted avg       0.56      0.56      0.56       129



In [34]:
confusion_matrix_results = confusion_matrix(y_test, predictions)

confusion_matrix_dataframe = pd.DataFrame(confusion_matrix_results,
                                         index = ['Actual 0', 'Actual 1'],
                                         columns = ['Predicted 0', 'Predicted 1'])
display(confusion_matrix_dataframe)

Predicted 0  Predicted 1
Actual 0           27           30
Actual 1           27           45

In [36]:
#Hyper-paramter tuning

In [37]:
params = {'max_depth': [3,6,10],
        'learning_rate': [0.01, 0.05, 0.1],
        'n_estimators': [100, 500, 1000],
        'colsample_bytree': [0.3, 0.7],
        'booster': ["gbtree", "dart"],
        'min_child_weight': [1, 3, 5],
        'gamma': [i/10.0 for i in range(0,4)]
         }

tunne_model = XGBClassifier()

In [38]:
# #Grid serach
# xg_grid = GridSearchCV(estimator=tunne_model, param_grid=params, cv=2, n_jobs=-1, verbose=1)
# xg_grid.fit(x_train, y_train)

In [39]:
# best_param = xg_grid.best_params_
# best_param

In [40]:
# xg_grid.best_score_

In [41]:
data.Trend.shift(1)
data.dropna(inplace = True)
data

Close        Volume  Difference  Trend  Target
Date                                                        
2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0
2017-12-27  2682.62  2.202080e+09        2.12      1     1.0
2017-12-28  2687.54  2.153330e+09        4.92      1     0.0
2017-12-29  2673.61  2.443490e+09      -13.93      0     1.0
2018-02-01  2695.81  3.367250e+09       22.20      1     1.0
...             ...           ...         ...    ...     ...
2020-09-07  3152.05  4.829020e+09      -17.89      0     1.0
2020-10-07  3185.04  4.515340e+09       32.99      1     0.0
2020-07-13  3155.22  4.890780e+09      -29.82      0     1.0
2020-07-14  3197.52  4.476170e+09       42.30      1     1.0
2020-07-15  3226.56  4.669760e+09       29.04      1     0.0

[642 rows x 5 columns]

In [42]:
def train_test_split(data,perc):
    data = data.values
    n = int(len(data) * (1 - perc))
    return data[:n], data[n:]

In [43]:
train, test = train_test_split(data,0.2)

In [44]:
#def sliding_window(train, window_size, horizon):
#    '''
#    sliding window generator.
#    '''
#    for i in range(len(train) - window_size - horizon + 1):
#        split_train = train[i:window_size+1]
#        split_val = train[i+window_size:window_size+1+horizon]
#        yield split_train, split_val

In [45]:
def rolling(train, min_train_size, horizon):
    '''
    rolling window generator.
    '''
    for i in range(len(train) - min_train_size - horizon + 1):
        split_train = train[i:min_train_size+1]
        split_val = train[i+min_train_size:min_train_size+1+horizon]
        yield split_train, split_val

In [46]:
cv_rolling = rolling(train, min_train_size=5, horizon=1)

print('data:{0}\n'.format(train))
i = 0
for cv_train, cv_val in cv_rolling:
    print(f'CV[{i+1}]')
    print(f'Train:\t{cv_train}')
    print(f'Val:\t{cv_val}')
    print('----')
    i+=1

data:[[ 2.68050e+03  1.96878e+09 -2.84000e+00  0.00000e+00  1.00000e+00]
 [ 2.68262e+03  2.20208e+09  2.12000e+00  1.00000e+00  1.00000e+00]
 [ 2.68754e+03  2.15333e+09  4.92000e+00  1.00000e+00  0.00000e+00]
 ...
 [ 3.23718e+03  3.42038e+09 -9.10000e+00  0.00000e+00  1.00000e+00]
 [ 3.25305e+03  3.72089e+09  1.58700e+01  1.00000e+00  1.00000e+00]
 [ 3.27470e+03  3.63839e+09  2.16500e+01  1.00000e+00  0.00000e+00]]

CV[1]
Train:	[[ 2.68050e+03  1.96878e+09 -2.84000e+00  0.00000e+00  1.00000e+00]
 [ 2.68262e+03  2.20208e+09  2.12000e+00  1.00000e+00  1.00000e+00]
 [ 2.68754e+03  2.15333e+09  4.92000e+00  1.00000e+00  0.00000e+00]
 [ 2.67361e+03  2.44349e+09 -1.39300e+01  0.00000e+00  1.00000e+00]
 [ 2.69581e+03  3.36725e+09  2.22000e+01  1.00000e+00  1.00000e+00]
 [ 2.71306e+03  3.53866e+09  1.72500e+01  1.00000e+00  1.00000e+00]]
Val:	[[2.71306e+03 3.53866e+09 1.72500e+01 1.00000e+00 1.00000e+00]
 [2.72399e+03 3.69526e+09 1.09300e+01 1.00000e+00 1.00000e+00]]
----
CV[2]
Train:	[[ 2.682

Val:	[]
----
CV[295]
Train:	[]
Val:	[]
----
CV[296]
Train:	[]
Val:	[]
----
CV[297]
Train:	[]
Val:	[]
----
CV[298]
Train:	[]
Val:	[]
----
CV[299]
Train:	[]
Val:	[]
----
CV[300]
Train:	[]
Val:	[]
----
CV[301]
Train:	[]
Val:	[]
----
CV[302]
Train:	[]
Val:	[]
----
CV[303]
Train:	[]
Val:	[]
----
CV[304]
Train:	[]
Val:	[]
----
CV[305]
Train:	[]
Val:	[]
----
CV[306]
Train:	[]
Val:	[]
----
CV[307]
Train:	[]
Val:	[]
----
CV[308]
Train:	[]
Val:	[]
----
CV[309]
Train:	[]
Val:	[]
----
CV[310]
Train:	[]
Val:	[]
----
CV[311]
Train:	[]
Val:	[]
----
CV[312]
Train:	[]
Val:	[]
----
CV[313]
Train:	[]
Val:	[]
----
CV[314]
Train:	[]
Val:	[]
----
CV[315]
Train:	[]
Val:	[]
----
CV[316]
Train:	[]
Val:	[]
----
CV[317]
Train:	[]
Val:	[]
----
CV[318]
Train:	[]
Val:	[]
----
CV[319]
Train:	[]
Val:	[]
----
CV[320]
Train:	[]
Val:	[]
----
CV[321]
Train:	[]
Val:	[]
----
CV[322]
Train:	[]
Val:	[]
----
CV[323]
Train:	[]
Val:	[]
----
CV[324]
Train:	[]
Val:	[]
----
CV[325]
Train:	[]
Val:	[]
----
CV[326]
Train:	[]
Val:	[]


In [47]:
#def cross_validation_score(model, train, cv, metric):
#    cv_scores = []
#    for cv_train, cv_test in cv:
#        model.fit(cv_train, cv_test)
#        preds = model.predict(horizon=len(cv_test))
#        score=metric(y_true=cv_test, y_pred=preds)
#        cv_scores.append(score)
#    return np.array(cv_scores)

In [48]:
#cv_rolling = rolling(train, window_size=5, horizon=1)

#cv_scores_1 = cross_validation_score(model, train=train, cv=cv_sliding, metric=accuracy_score)

In [49]:
data = data.reset_index()
data.Date = data.Date.astype("object")
data.Date = pd.to_datetime(data.Date)

data["Sentiment"] = np.zeros(data.shape[0])
data["compound"] = np.zeros(data.shape[0])
data.head()

Date    Close        Volume  Difference  Trend  Target  Sentiment  \
0 2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0        0.0   
1 2017-12-27  2682.62  2.202080e+09        2.12      1     1.0        0.0   
2 2017-12-28  2687.54  2.153330e+09        4.92      1     0.0        0.0   
3 2017-12-29  2673.61  2.443490e+09      -13.93      0     1.0        0.0   
4 2018-02-01  2695.81  3.367250e+09       22.20      1     1.0        0.0   

   compound  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0

In [50]:
#Merge with sentiment for News
data1 = pd.read_csv("final_polarity_data.csv")[['created_at', 'prediction_vader', 'compound']]
data1.columns = ['Date', 'Sentiment', 'compound']
data1.Date = pd.to_datetime(data1.Date)
data1.head()

Date  Sentiment  compound
0 2020-04-15          1    0.9972
1 2020-06-25          1    0.9993
2 2020-06-04          1    0.9989
3 2020-07-03          1    0.9881
4 2020-07-09          1    0.9994

In [51]:
#d = data.copy()
#d1 = data1.copy()

In [52]:
# Generating copy of both datasets
d = data.copy()
d1 = data1.copy()

# Attaching sentiment
rows = []
for i in d.Date:
    for j in d1.Date:
        if i==j:
            index = d[d.Date == i].index[0]
            new_row = dict(d.iloc[index,:])
            
            sent = d1[d1.Date == i].Sentiment.values[0]
            new_row["Sentiment"] = sent
            
            comp = d1[d1.Date == i].compound.values[0]
            new_row["compound"] = comp
            
            rows.append(new_row)
            
new_data = pd.DataFrame(data=rows, columns=d.columns)
new_data.set_index('Date', inplace=True)
new_data.head()

Close        Volume  Difference  Trend  Target  Sentiment  \
Date                                                                      
2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0         -1   
2017-12-27  2682.62  2.202080e+09        2.12      1     1.0          1   
2018-02-01  2695.81  3.367250e+09       22.20      1     1.0          1   
2018-03-01  2713.06  3.538660e+09       17.25      1     1.0          1   
2018-05-01  2743.15  3.236620e+09       19.16      1     1.0          1   

            compound  
Date                  
2017-12-26    0.0000  
2017-12-27    0.3400  
2018-02-01    0.7906  
2018-03-01    0.7430  
2018-05-01    0.4588

In [53]:
#new_data = pd.DataFrame(data=rows, columns=d.columns)
#new_data.set_index('Date', inplace=True)

In [54]:
new_data

Close        Volume  Difference  Trend  Target  Sentiment  \
Date                                                                      
2017-12-26  2680.50  1.968780e+09       -2.84      0     1.0         -1   
2017-12-27  2682.62  2.202080e+09        2.12      1     1.0          1   
2018-02-01  2695.81  3.367250e+09       22.20      1     1.0          1   
2018-03-01  2713.06  3.538660e+09       17.25      1     1.0          1   
2018-05-01  2743.15  3.236620e+09       19.16      1     1.0          1   
...             ...           ...         ...    ...     ...        ...   
2020-06-07  3179.72  4.736450e+09       49.71      1     0.0          1   
2020-07-07  3145.32  4.563700e+09      -34.40      0     1.0          1   
2020-07-13  3155.22  4.890780e+09      -29.82      0     1.0          1   
2020-07-14  3197.52  4.476170e+09       42.30      1     1.0          1   
2020-07-15  3226.56  4.669760e+09       29.04      1     0.0          1   

            compound  
Date                  
2017-12-26    0.0000  
2017-12-27    0.3400  
2018-02-01    0.7906  
2018-03-01    0.7430  
2018-05-01    0.4588  
...              ...  
2020-06-07    0.9482  
2020-07-07    0.9977  
2020-07-13    0.9994  
2020-07-14    0.9997  
2020-07-15    0.9993  

[511 rows x 7 columns]

In [55]:
new_data.to_csv("news_sent_data.csv")

In [56]:
#Run model again with sentiment as additional feature
#x = new_data.drop('Target', axis=1)
#y = new_data.Target

In [57]:
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [58]:
#best_param

In [59]:
# Let's train our new model on the best parameters that we have calculated with GridSearchCV
#model = XGBClassifier(booster='gbtree', colsample_bytree=0.3, gamma=0.3, min_child_weight=3, learning_rate=0.01, max_depth=6, n_estimators=100)
#model.fit(x_train, y_train)

#train_score = model.score(x_train, y_train)
#test_score = model.score(x_test, y_test)

#print('Train score: ', train_score)
#print('Test score: ', test_score)

In [60]:
# Let's make prediction
#y_pred = model.predict(x_test)

In [61]:
#pd.DataFrame({"Original": y_test, "Predicted": y_pred})

In [62]:
#accu_sent = accuracy_score(y_test, y_pred)
#accu_sent

In [63]:
#from sklearn.metrics import plot_confusion_matrix
#plot_confusion_matrix(model, x_test, y_test)

In [64]:
#print('Accuracy with Sentiment data : ', accu_sent)
#print('Accuracy without Sentiment data : ', accuracy)